# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        admin_user_mock:
            id: app.security.admin_user_mock_provider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                default_target_path: /
            logout:       true
            anonymous:    true

            light_saml_sp:
                # Symfony's default options
                # provides user from given username
                provider: admin_user_mock
                login_path: /backoffice/saml/login
                check_path: /backoffice/saml/login_check
                require_previous_session: false
#                username_mapper: lightsaml_sp.username_mapper.simple

    access_control:
        - { path: ^/backoffice/saml, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/accaunt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/chat, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY }
